### PR TITLE
Add a local sync command.

### PR DESCRIPTION
**Pull request by Jelle-S**

### CODE REVIEW

**Comment by Jelle-S** [comment]
in our setup we currently have {appdir}/files/public and {appdir}/files/private, and sites/default/files is linked to {appdir}/files/public. The files backup backs up {appdir}/files so it contains both public and private

**Comment by daften** [comment]
Isn't local file dir wrong then? Since it will contain public and private folders beneath sites/default/files?

**Comment by Jelle-S** [comment]
Yes, that'll need a manual action from the dev for now (or defining it that way in his settings.local.php or something), since the private path on the local machine can be anything really... Or do you have some suggestions?

**Comment by daften** [comment]
No, not how to handle private files, but I'd make sure that public files are synced correctly to the correct folder (and not in a subfolder).

**Pull request merged**
